---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: data-pipeline-dev
spec:
  encryptedData:
    rootPassword: AgCQyLZaeR05rl3vW8HE5sJ5lNnRpwhF26hAax4jUknXgCbdmJYyCOPwvu9RH4nF3vusMrhiP2J8rHPnoLyE/Qo0yuRpWSj25UBsiDUPZPcrwj6BPLSpGcAqeiUJn/rzLOBPU4YxVR/SdKlY2W+5sQ55OhAg+25/B+bCh/rZJa5PsB+/4ql1mGGJINztCb10x6lSgxp1lwUW3Y/xW8NUMT/9oJ9CrRyQIxk6j+ZUK62dU0l1TV7umTIxtWnSMzaT1BE3o6RWFkva8JbRKwEmNfbTifHxCJXGjd6RoCJdXaXkR522jP7wHlQ0LUPe/SWDYH82RQdfD/sN3uAhx/CBtJh7YiYOOL9U6zpc7aYpENeMUhmt9Ecs9lUzGBwfLNmHgiPMSSRdbSI8ImROER+j2tSCeYZwQUctB9dQXBbPjhYvHDu492c04BjpxcU8XxaaF47pStWfdPhCpDZUsl1ESUnkSPf7OJiLm9cAededscN/SGyZzcQHDQVr/gmU/CDU1cHa1i4jFOzUFpe6QvtGzI16CdkbUO7FpX8yrGu5DaKcc2y/DjTne+5GPKv4p7tGnWosyw9pbckKavqBfyhTa8tbyCYokBwJHLoFA4DKjGMEGYO1HAnkMJN13gyNqcdXYjMvct4uyYMtCldtV+GnJHMnEkZA7S9t9HJ04165Ke+Z+FLbIADSJMVNE0XmuqaeMcBualSXUJAVPwX3
    rootUser: AgBzcH9kzS/mMphd3dKrscO5H492gG6dBWWkdiWz61EfymhCinBSO5AFAicfgMK6AXhX0tyqJSpNg1giGyIk8jTtrRiks32tfxT3csVc+bhL8us6bPqM2kksGw7MC4InrOy4QR6FhjhlZQ9NSrjwylaqt88dbUstOMdngRtrs0oOHnVp9rAn9hl58SGwaVgSiZ2HRsu0swdER62loJDDoXGCZUmyr2vit+jeSJxqkR7nVDxNM3wG9jRQkL2DSjx7ywAkj50EGjD5/HN/pD2RYTfyBproy0x3Ecw/ezOTRGrEKH8XoILtqL4t3tosjyOCQowR/BHiWyNbCflxnitq/YlqfbK8iMms5pfgKuBpJPS8arTRVqGw0uAEbG26mQQVOokq5v4PCp7LK+cXDvWaa7GiZ7sLuPXyH4wFLWdnjaWJo58E7xIlAjD2E1pxkge+N0RTf7QLfkJ1/2ZVjatJoLhhbEvM2nTrv+fPoPG6mZIoKajxDS40vvt8GGCjf9x++Kvf6ZHJAPBowNYJF0lQuSv6BpTHj7x6PKAaYRHvCHO9slZaI/QpK2uWOW+Rqn9vV+qYvLcbTGGbZRyqKEP6n2U3q7hoLKrxB6U1hHxWFN46xIS3cy+X8oNaJ/Q08E+qPWz1hkTiVLesgmSNBnVIEbD+lOt12lNRPaNv1/o3WQjNJU/+f+PmqZeuzvbz/GlqhC+6TVZ0cGZD1Hwm
  template:
    metadata:
      name: minio-credentials
      namespace: data-pipeline-dev
